include:
  template: Auto-DevOps.gitlab-ci.yml
variables:
  POSTGRES_ENABLED: "false"
  STAGING_ENABLED: "true"
  TEST_DISABLED: "true"

staging:
  variables:
    KUBE_NAMESPACE: "myopic-mces-data-staging"
  environment:
      name: staging
      url: http://$KUBE_INGRESS_BASE_DOMAIN/$CI_PROJECT_PATH_SLUG-staging/

production_manual:
  variables:
    KUBE_NAMESPACE: "myopic-mces-data"
#    ADDITIONAL_HOSTS: ""
  environment:
      name: production
      url: http://$KUBE_INGRESS_BASE_DOMAIN/$CI_PROJECT_PATH_SLUG/

default:
  tags:
  - docker
