include:
  template: Auto-DevOps.gitlab-ci.yml
variables:
  POSTGRES_ENABLED: "false"
  STAGING_ENABLED: "false"
  TEST_DISABLED: "true"
build:
  before_script:
    - |
      if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]]; then
        export SENTRY_PUBLISH_RELEASE="{setCommits: {auto: true, ignoreMissing: true}}"
      fi
  services:
    - name: 'docker:20.10.6-dind'
      command: ['--tls=false', '--host=tcp://0.0.0.0:2375', '--mtu=1300']

staging:
  variables:
    KUBE_NAMESPACE: "myopic-mces-data-staging"
  environment:
      name: staging
      url: http://www.csi-fingerid.uni-jena.de/$CI_PROJECT_PATH_SLUG-staging/

production_manual:
  variables:
    KUBE_NAMESPACE: "myopic-mces-data"
#    ADDITIONAL_HOSTS: ""
  environment:
      name: production
      url: http://www.csi-fingerid.uni-jena.de/$CI_PROJECT_PATH_SLUG/

