include:
  template: Auto-DevOps.gitlab-ci.yml
variables:
  POSTGRES_ENABLED: "false"
  STAGING_ENABLED: "true"
  TEST_DISABLED: "true"

staging:
  variables:
    KUBE_NAMESPACE: "myopic-mces-data-staging"
  environment:
      name: staging
      url: http://staging.mces-data.$KUBE_INGRESS_BASE_DOMAIN/

production_manual:
  variables:
    KUBE_NAMESPACE: "myopic-mces-data"
#    ADDITIONAL_HOSTS: ""
  environment:
      name: production
      url: http://mces-data.$KUBE_INGRESS_BASE_DOMAIN/

default:
  tags:
  - docker
